version: "3.9"
services:
#  bot-1:
#    build: backend
  nats:
    image: nats
    ports:
      - "8222:8222"
      - "4222:4222"
    command: "-js -n nats --cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 --routes=nats://ruser:T0pS3cr3t@localhost:6222"
    networks: ["nats"]
  nats-1:
    image: nats
    ports:
      - "4223:4222"
    command: "-js -n nats-1 --cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks: ["nats"]
    depends_on: ["nats"]
  nats-2:
    image: nats
    ports:
      - "4224:4222"
    command: "-js -n nats-2 --cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks: ["nats"]
    depends_on: ["nats"]

networks:
  nats:
    name: nats
