version: "3.9"
services:
#  bot-1:
#    build: backend



  # NATS

  nats:
    image: nats
    ports:
      - "8222:8222"
      - "4222:4222"
    command: "-js -n nats --cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 --routes=nats://ruser:T0pS3cr3t@localhost:6222"
    networks: ["nats"]

  nats-1:
    image: nats
    ports:
      - "4223:4222"
    command: "-js -n nats-1 --cluster_name NATS --cluster nats://0.0.0.0:6223 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks: ["nats"]
    depends_on: ["nats"]

  nats-2:
    image: nats
    ports:
      - "4224:4222"
    command: "-js -n nats-2 --cluster_name NATS --cluster nats://0.0.0.0:6224 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks: ["nats"]
    depends_on: ["nats"]



  # ScyllaDB

  scylla-node1:
    container_name: scylla-node1
    image: scylladb/scylla
    ports:
      - "9042:9042"
      - "10000:10000"
    restart: always
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    networks:
      web:

  scylla-node2:
    container_name: scylla-node2
    image: scylladb/scylla
    ports:
      - "9043:9042"
    restart: always
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    networks:
      web:

  scylla-node3:
    container_name: scylla-node3
    image: scylladb/scylla
    ports:
      - "9044:9042"
    restart: always
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    networks:
      web:

networks:
  nats:
    name: nats
  web:
    driver: bridge
