export NATS_URL := "nats://localhost:4222,nats://localhost:4223,nats://localhost:4224"
export SCYLLA_ADDRS := "localhost:9042,localhost:9043,localhost:9044"

test-all:
    go test -v ./...

run-bot:
    go run cmd/bot.go